### ISSUE TITLE
A value of type 'DialogThemeData' can't be assigned to a variable of type 'DialogTheme'

### ISSUE THREAD

**Issue by ali-raza-flutter** [hezbr/csc_picker_plus#1]
**A value of type 'DialogThemeData' can't be assigned to a variable of type 'DialogTheme'**

After updating flutter version to 3.27.0 I am encountering this issue.

"Error (Xcode): ../../../.pub-cache/hosted/pub.dev/csc_picker_plus-0.0.2/lib/dropdown_with_search.dart:351:49: Error: A value of type 'DialogThemeData' can't be assigned to a variable of type 'DialogTheme'."

**Flutter Doctor result**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.0, on macOS 15.2 24C101 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.96.0)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Ali Raza’s iPhone. Ensure the device is unlocked and attached with a cable or associated
      with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Muhammad Ali’s iPhone. Ensure the device is unlocked and attached with a cable or associated
      with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

**Comment by tony123S** [comment]
@ali-raza-flutter you can use this first while waiting for author to update it.

```
csc_picker_plus:
    git:
      url: git@github.com:tony123S/csc_picker_plus.git
```

**Comment by hezbr** [comment]
@ali-raza-flutter Thank you for your note. 
The issue has been resolved in `csc_picker_plus 0.0.3` package.

You can check it and use it on the link [csc_picker_plus](https://pub.dev/packages/csc_picker_plus).

**Comment by efdee1** [comment]
> [@ali-raza-flutter](https://github.com/ali-raza-flutter) Thank you for your note. The issue has been resolved in `csc_picker_plus 0.0.3` package.
> 
> You can check it and use it on the link [csc_picker_plus](https://pub.dev/packages/csc_picker_plus).
 no its still there

**Comment by shahim-np** [comment]
Hello @hezbr , 

the issue is still there, I'm using flutter 3.22.1
